# Generated by Django 4.1.7 on 2023-04-25 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40, verbose_name='title')),
            ],
            options={
                'verbose_name': 'amenity',
                'verbose_name_plural': 'amenities',
                'db_table': 'amenity',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=14, verbose_name='phone')),
                ('citizenship', models.CharField(max_length=40, verbose_name='citizenship')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(blank=True, max_length=40, null=True, verbose_name='company')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('star_rating', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='star rating')),
                ('rooms_quantity', models.PositiveIntegerField(verbose_name='rooms quantity')),
                ('phone', models.CharField(blank=True, max_length=14, null=True, verbose_name='phone')),
                ('check_in', models.CharField(max_length=5, verbose_name='check in')),
                ('check_out', models.CharField(max_length=5, verbose_name='check out')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('country', models.CharField(max_length=40, verbose_name='country')),
                ('state', models.CharField(blank=True, max_length=40, null=True, verbose_name='state')),
                ('city', models.CharField(max_length=40, verbose_name='city')),
                ('street', models.CharField(max_length=40, verbose_name='street')),
                ('building', models.CharField(max_length=5, verbose_name='building')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
            ],
            options={
                'verbose_name': 'hotel',
                'verbose_name_plural': 'hotels',
                'db_table': 'hotel',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=40, verbose_name='type')),
                ('name', models.CharField(max_length=40, verbose_name='name')),
                ('code', models.CharField(max_length=40, verbose_name='code')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('capacity', models.PositiveSmallIntegerField(verbose_name='capacity')),
                ('double_bed', models.PositiveSmallIntegerField(verbose_name='double bed')),
                ('single_bed', models.PositiveSmallIntegerField(verbose_name='single bed')),
                ('area', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='area')),
                ('safe', models.BooleanField(blank=True, default=False, null=True, verbose_name='safe')),
                ('tv', models.BooleanField(blank=True, default=False, null=True, verbose_name='tv')),
                ('soundproofing', models.BooleanField(blank=True, default=False, null=True, verbose_name='soundproofing')),
                ('telephone', models.BooleanField(blank=True, default=False, null=True, verbose_name='telephone')),
                ('heating', models.BooleanField(blank=True, default=False, null=True, verbose_name='heating')),
                ('wardrobe', models.BooleanField(blank=True, default=False, null=True, verbose_name='wardrobe')),
                ('shower', models.BooleanField(blank=True, default=False, null=True, verbose_name='shower')),
                ('minibar', models.BooleanField(blank=True, default=False, null=True, verbose_name='minibar')),
                ('air_conditioning', models.BooleanField(blank=True, default=False, null=True, verbose_name='air conditioning')),
                ('bath', models.BooleanField(blank=True, default=False, null=True, verbose_name='bath')),
                ('desk', models.BooleanField(blank=True, default=False, null=True, verbose_name='desk')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_app.hotel')),
            ],
            options={
                'verbose_name': 'room',
                'verbose_name_plural': 'rooms',
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('payment', models.CharField(blank=True, choices=[('cash', 'cash'), ('credit_card', 'credit card')], max_length=40, null=True, verbose_name='payment')),
                ('is_actual', models.BooleanField(default=True, verbose_name='is actual')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_app.client')),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
                'db_table': 'reservation',
                'ordering': ['is_actual'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='quantity')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_app.amenity')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_app.hotel')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_app.reservation')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='HotelAmenity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_app.amenity')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_app.hotel')),
            ],
            options={
                'db_table': 'hotel_amenity',
            },
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(through='hotels_app.HotelAmenity', to='hotels_app.amenity', verbose_name='amenities'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='date')),
                ('is_booked', models.BooleanField(default=False, verbose_name='is booked')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels_app.reservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_app.room')),
            ],
            options={
                'verbose_name': 'booking',
                'verbose_name_plural': 'bookings',
                'db_table': 'booking',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='amenity',
            name='hotels',
            field=models.ManyToManyField(through='hotels_app.HotelAmenity', to='hotels_app.hotel', verbose_name='hotels'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='room_price_check'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(('capacity__gt', 0)), name='capacity_check'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(('double_bed__gte', 0)), name='double_bed_check'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(('single_bed__gte', 0)), name='single_bed_check'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.CheckConstraint(check=models.Q(('area__gt', 0)), name='area_check'),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('hotel', 'code')},
        ),
        migrations.AddConstraint(
            model_name='reservation',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='reserv_price_check'),
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gt', 0)), name='item_quantity_check'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('reservation', 'hotel', 'amenity')},
        ),
        migrations.AddConstraint(
            model_name='hotelamenity',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0)), name='amenity_price_check'),
        ),
        migrations.AlterUniqueTogether(
            name='hotelamenity',
            unique_together={('hotel', 'amenity')},
        ),
        migrations.AddIndex(
            model_name='hotel',
            index=models.Index(fields=['name'], name='hotel_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.CheckConstraint(check=models.Q(('star_rating__gte', 0), ('star_rating__lte', 5)), name='star_rate_check'),
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.CheckConstraint(check=models.Q(('rooms_quantity__gt', 0)), name='rooms_quan_check'),
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.CheckConstraint(check=models.Q(('latitude__gte', 0), ('latitude__lte', 90)), name='latitude_check'),
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.CheckConstraint(check=models.Q(('longitude__gte', 0), ('longitude__lte', 180)), name='longitude_check'),
        ),
    ]
