# Generated by Django 4.1.7 on 2023-04-27 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='reservation',
            name='reserv_price_check',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='price',
        ),
        migrations.RemoveField(
            model_name='room',
            name='name',
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hotels_app.reservation'),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('standart', 'Standart'), ('superior', 'Superior'), ('suite', 'Suite'), ('family_room', 'Family room'), ('deluxe', 'Deluxe'), ('apartments', 'Apartments'), ('studio', 'Studio'), ('duplex', 'Duplex'), ('business_room', 'Business room'), ('royal_suite', 'Royal suite')], max_length=40, verbose_name='type'),
        ),
        # migrations.AlterUniqueTogether(
        #     name='booking',
        #     unique_together={('date', 'room')},
        # ),
    ]
