# Generated by Django 4.2.1 on 2023-06-06 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelamenity',
            name='price',
        ),
    ]
