# Generated by Django 4.1.7 on 2023-04-29 12:08

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import hotels_app.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0002_remove_reservation_reserv_price_check_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name': 'amenity', 'verbose_name_plural': 'amenities'},
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-check_in', '-check_out'], 'verbose_name': 'booking', 'verbose_name_plural': 'bookings'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name': 'hotel', 'verbose_name_plural': 'hotels'},
        ),
        migrations.AlterModelOptions(
            name='hotelamenity',
            options={'verbose_name': 'hotel amenity', 'verbose_name_plural': 'hotel amenities'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'reservation', 'verbose_name_plural': 'reservations'},
        ),
        migrations.RemoveConstraint(
            model_name='hotel',
            name='latitude_check',
        ),
        migrations.RemoveConstraint(
            model_name='hotel',
            name='longitude_check',
        ),
        # migrations.AlterUniqueTogether(
        #     name='booking',
        #     unique_together=set(),
        # ),
        migrations.RemoveField(
            model_name='reservation',
            name='is_actual',
        ),
        migrations.AddField(
            model_name='booking',
            name='check_in',
            field=models.DateField(default=datetime.date.today, verbose_name='check_in'),
        ),
        migrations.AddField(
            model_name='booking',
            name='check_out',
            field=models.DateField(default=hotels_app.models.get_checkout_date, verbose_name='check_out'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotels_app.reservation'),
        ),
        migrations.AlterField(
            model_name='client',
            name='citizenship',
            field=models.CharField(choices=[('afghanistan', 'Afghanistan'), ('albania', 'Albania'), ('algeria', 'Algeria')], max_length=40, verbose_name='citizenship'),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[hotels_app.models.validate_birth]),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=14, region=None, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='latitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)], verbose_name='latitude'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='longitude',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)], verbose_name='longitude'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=14, null=True, region=None, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='star_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='star rating'),
        ),
        migrations.AlterField(
            model_name='hotelamenity',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='quantity'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='price'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('room', 'check_in', 'check_out')},
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.CheckConstraint(check=models.Q(('latitude__gte', -90), ('latitude__lte', 90)), name='latitude_check'),
        ),
        migrations.AddConstraint(
            model_name='hotel',
            constraint=models.CheckConstraint(check=models.Q(('longitude__gte', -180), ('longitude__lte', 180)), name='longitude_check'),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='is_booked',
        ),
    ]
