# Generated by Django 4.1.7 on 2023-04-30 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0003_alter_amenity_options_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'ordering': ['title'], 'verbose_name': 'amenity', 'verbose_name_plural': 'amenities'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name'], 'verbose_name': 'hotel', 'verbose_name_plural': 'hotels'},
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('check_in', 'check_out', 'room')},
        ),
    ]
