# Generated by Django 4.1.7 on 2023-05-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels_app', '0004_alter_amenity_options_alter_hotel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='title',
            field=models.CharField(max_length=40, unique=True, verbose_name='title'),
        ),
    ]
